"""Generates the fictional sample player pool.

Realistic *shape*, invented *people*. The point is that every model path the app
takes has plausible data to run against — positional value curves that actually
flatten at the right places, ADP uncertainty that widens as you go deeper, real
value cliffs, a handful of injuries and suspensions, and boom/bust players whose
ceiling and floor genuinely diverge. Without those, whole features (the upside
lens, positional scarcity, the injury discount) are structurally unreachable
and a new user would conclude they are broken.

Everything is deterministic: the same seed produces the same pool, so a bug found
in a sample draft can be reproduced exactly.

**This is not real data.** Names are generated from invented lists, and the
projections are drawn from a parametric model, not from any provider. Every entry
point here labels the output as sample data, and
:data:`core.constants.SAMPLE_DATA_BANNER` travels with the pool metadata into the
UI.
"""

from __future__ import annotations

import random
from dataclasses import dataclass

import pandas as pd

from core.constants import (
    NFL_TEAMS,
    PLAYER_IMPORT_COLUMNS,
    REPLACEMENT_RANK_PER_TEAM,
)
from core.enums import InjuryStatus, Position

from .names import FIRST_NAMES, LAST_NAMES

SAMPLE_SEED = 20260401
"""Default RNG seed. Fixed so the bundled dataset is byte-identical every run."""

DEFAULT_PLAYER_COUNT = 260
"""Players generated by default.

Sized above a 12×16 draft's 192 picks so a full draft never exhausts the pool and
the late rounds still involve a real choice rather than taking whoever is left.
"""


# ─────────────────────────────────────────────────────────────────────────────
# Positional shape
# ─────────────────────────────────────────────────────────────────────────────
@dataclass(frozen=True, slots=True)
class PositionShape:
    """How one position's value and market price are distributed across its pool.

    Parameters rather than a table of players, so the pool scales to any size
    without hand-editing hundreds of rows. Value and price are described
    *separately* — points come from the decay curve, the draft board comes from
    the ADP curve — because in real fantasy football they genuinely disagree. A
    quarterback outscores every running back and still goes two rounds later.
    Deriving ADP from projections instead would collapse that, and would also make
    the "best value available" lens identical to "best player available".
    """

    count: int
    """How many players of this position exist in the pool."""
    top_points: float
    """Projected season points for the position's best player."""
    decay: float
    """Points lost per rank at the top of the curve."""
    curve: float
    """Curve exponent. Above 1.0 the drop-off steepens with rank (a cliff after
    the elite few); below 1.0 it flattens (a wide, interchangeable middle)."""
    volatility: float
    """Ceiling/floor spread as a share of projection, for the median player."""
    adp_anchor: float
    """Roughly where the position's best player goes, in overall picks."""
    adp_growth: float
    """Exponent on rank in ``adp_anchor * rank ** adp_growth``.

    Above 1.0 the position's price rises faster than its rank, so the market
    exhausts it quickly (RB); below 1.0 the tail is cheap and slow to drain, which
    is why waiting on a quarterback works.
    """

    def points_at(self, rank: int) -> float:
        """Projected points for the ``rank``-th best player at this position."""
        depth = max(0, rank - 1) / max(1, self.count - 1)
        return max(12.0, self.top_points - self.decay * self.count * (depth ** self.curve))

    def expected_adp(self, rank: int) -> float:
        """Where the market takes the ``rank``-th player at this position."""
        return self.adp_anchor * (max(1, rank) ** self.adp_growth)


POSITION_SHAPES: dict[Position, PositionShape] = {
    # Quarterbacks: highest raw scoring, latest market price, flattest ADP curve.
    # QB1 goes around pick 20 and QB12 around pick 100 — so QB8 costs a fraction
    # of QB2 while scoring nearly as much, which is what makes the late-QB
    # archetype a real strategy rather than a mistake the model tolerates.
    Position.QB: PositionShape(
        count=34, top_points=402.0, decay=6.4, curve=0.85, volatility=0.16,
        adp_anchor=19.0, adp_growth=0.66,
    ),
    # Running backs: the steepest cliff in both value and price. A handful of
    # every-week starters, then a long tail of committee backs. The steep ADP
    # growth is what makes the scarcity lens fire at RB first.
    Position.RB: PositionShape(
        count=68, top_points=336.0, decay=4.1, curve=1.35, volatility=0.26,
        adp_anchor=1.7, adp_growth=1.19,
    ),
    # Receivers: deepest position, gentlest value decay, and priced alongside RBs
    # at the top — the top of a real board alternates between the two.
    Position.WR: PositionShape(
        count=84, top_points=328.0, decay=2.9, curve=1.05, volatility=0.22,
        adp_anchor=1.5, adp_growth=1.14,
    ),
    # Tight ends: one or two genuine difference-makers and then nothing. The
    # sharpest value cliff in fantasy football, and the reason the elite-TE
    # archetype exists — TE1 is worth a second-round pick, TE6 is not worth a
    # seventh.
    Position.TE: PositionShape(
        count=32, top_points=272.0, decay=7.6, curve=1.55, volatility=0.24,
        adp_anchor=13.0, adp_growth=0.92,
    ),
    # Kickers and defences: nearly flat value, and a market that ignores them
    # until the last two rounds no matter how many points they score.
    Position.K: PositionShape(
        count=22, top_points=158.0, decay=2.4, curve=0.70, volatility=0.12,
        adp_anchor=150.0, adp_growth=0.14,
    ),
    Position.DST: PositionShape(
        count=22, top_points=172.0, decay=3.1, curve=0.80, volatility=0.20,
        adp_anchor=142.0, adp_growth=0.16,
    ),
}

POSITION_MIX: dict[Position, float] = {
    Position.QB: 0.13,
    Position.RB: 0.26,
    Position.WR: 0.32,
    Position.TE: 0.12,
    Position.K: 0.085,
    Position.DST: 0.085,
}
"""Share of the pool at each position when scaling to a requested size.

Sums to 1.0. Used only when the caller asks for a size other than the sum of the
:data:`POSITION_SHAPES` counts.
"""

# ─────────────────────────────────────────────────────────────────────────────
# Draft-board behaviour
# ─────────────────────────────────────────────────────────────────────────────
ADP_NOISE_SHARE = 0.11
"""Market disagreement about a player, as a share of his expected ADP.

Proportional rather than absolute because consensus is tight at the top of the
board and loose at the bottom: nobody disagrees by four picks about the first pick
in the draft, and everybody disagrees by more than four about pick 150.

Non-zero on purpose. A board that is a perfect function of position rank makes
"best value available" trivially identical to "best player available", so the
value lens could be badly wrong and the sample data would never show it.
"""

ADP_STDEV_FLOOR = 0.9
ADP_STDEV_PER_PICK = 0.085
"""ADP standard deviation grows with ADP: consensus on pick 1 is near-total,
while a pick-140 player might go anywhere in a 40-pick window. Roughly matches
the spread real ADP tables report."""

INJURY_MIX: tuple[tuple[InjuryStatus, float], ...] = (
    (InjuryStatus.QUESTIONABLE, 0.055),
    (InjuryStatus.DOUBTFUL, 0.012),
    (InjuryStatus.OUT, 0.010),
    (InjuryStatus.IR, 0.016),
    (InjuryStatus.PUP, 0.008),
)
"""Status → share of the pool. The remainder are healthy.

Kept low and realistic. Every one of these exercises a different branch: the
injury discount in the pick model, the safety lens's penalty, and — for IR — the
``is_available_flag`` path that keeps an unusable player off the board.
"""

SUSPENDED_RATE = 0.010
ROOKIE_RATE = 0.16
BOOM_BUST_RATE = 0.14
"""Share of players given a deliberately wide outcome distribution.

These are the players the upside and safety lenses are built to disagree about.
Without any, both lenses converge on the highest projection and the trade-off the
app exists to surface never appears.
"""

BYE_WEEKS: tuple[int, ...] = tuple(range(5, 15))
"""Weeks 5-14, matching the real bye structure. Assigned per NFL team, not per
player, so teammates share a bye and the bye-stack warning is reachable."""


# ─────────────────────────────────────────────────────────────────────────────
# Generation
# ─────────────────────────────────────────────────────────────────────────────
def _position_counts(total: int) -> dict[Position, int]:
    """Player count per position for a pool of ``total`` players.

    Uses the natural :data:`POSITION_SHAPES` counts when the caller wants that
    size, and otherwise scales by :data:`POSITION_MIX` — with kickers and
    defences floored at one per team-ish, because a pool with three kickers makes
    the last two rounds of a 12-team draft impossible to fill legally.
    """
    natural = sum(shape.count for shape in POSITION_SHAPES.values())
    if total == natural:
        return {position: shape.count for position, shape in POSITION_SHAPES.items()}

    counts: dict[Position, int] = {}
    for position, share in POSITION_MIX.items():
        floor = 14 if position in (Position.K, Position.DST) else 6
        counts[position] = max(floor, int(round(total * share)))
    # Reconcile rounding against the requested total by adjusting the deepest
    # position, which is where one player more or less changes nothing.
    drift = total - sum(counts.values())
    counts[Position.WR] = max(6, counts[Position.WR] + drift)
    return counts


def _unique_names(rng: random.Random, count: int) -> list[str]:
    """``count`` distinct invented names.

    Distinct because the importer rejects duplicate name+position pairs, and a
    sample file that trips its own validator would teach a user the wrong thing
    about their own file.
    """
    names: list[str] = []
    seen: set[str] = set()
    firsts, lasts = list(FIRST_NAMES), list(LAST_NAMES)
    while len(names) < count:
        candidate = f"{rng.choice(firsts)} {rng.choice(lasts)}"
        if candidate in seen:
            continue
        seen.add(candidate)
        names.append(candidate)
    return names


def _team_byes(rng: random.Random) -> dict[str, int]:
    """One bye week per NFL team, spread as evenly as the weeks allow."""
    teams = list(NFL_TEAMS)
    rng.shuffle(teams)
    return {team: BYE_WEEKS[index % len(BYE_WEEKS)] for index, team in enumerate(teams)}


def _draw_status(rng: random.Random) -> tuple[InjuryStatus, bool]:
    """An injury status and suspension flag for one player."""
    roll = rng.random()
    cumulative = 0.0
    for status, rate in INJURY_MIX:
        cumulative += rate
        if roll < cumulative:
            return status, False
    if roll < cumulative + SUSPENDED_RATE:
        return InjuryStatus.SUSPENDED, True
    return InjuryStatus.HEALTHY, False


@dataclass(slots=True)
class _Draft:
    """One generated player before ADP ordering is applied across positions."""

    name: str
    position: Position
    position_rank: int
    nfl_team: str
    bye_week: int
    projection: float
    ceiling: float
    floor: float
    risk_score: float
    experience: int
    is_rookie: bool
    injury_status: InjuryStatus
    suspended: bool
    market_pick: float
    """Where the market takes him: the ordering key for the draft board."""
    notes: str = ""


def _generate(rng: random.Random, total: int) -> list[_Draft]:
    counts = _position_counts(total)
    names = iter(_unique_names(rng, sum(counts.values())))
    byes = _team_byes(rng)
    teams = list(NFL_TEAMS)
    drafts: list[_Draft] = []

    for position, count in counts.items():
        shape = POSITION_SHAPES[position]
        for rank in range(1, count + 1):
            projection = shape.points_at(rank)
            # Deeper players are more volatile in both directions: the further
            # down the board, the less anyone knows.
            depth = (rank - 1) / max(1, count - 1)
            volatility = shape.volatility * (0.75 + 0.75 * depth)
            if rng.random() < BOOM_BUST_RATE:
                volatility *= 2.1
            ceiling = projection * (1.0 + volatility)
            floor = projection * max(0.15, 1.0 - volatility * 0.85)

            experience = 0 if rng.random() < ROOKIE_RATE else rng.randint(1, 12)
            status, suspended = _draw_status(rng)
            team = rng.choice(teams)
            # Where the market takes him: the position's own ADP curve, jittered
            # proportionally so the board is not a perfect function of rank.
            expected = shape.expected_adp(rank)
            market = max(
                0.5, expected + rng.gauss(0.0, expected * ADP_NOISE_SHARE)
            )
            drafts.append(_Draft(
                name=next(names),
                position=position,
                position_rank=rank,
                nfl_team=team,
                bye_week=byes.get(team, BYE_WEEKS[0]),
                projection=round(projection, 1),
                ceiling=round(ceiling, 1),
                floor=round(floor, 1),
                risk_score=round(min(0.95, volatility * 1.4), 3),
                experience=experience,
                is_rookie=experience == 0,
                injury_status=status,
                suspended=suspended,
                market_pick=market,
            ))
    return drafts


def _value_over_replacement(
    drafts: list[_Draft], team_count: int
) -> dict[str, float]:
    """Each player's points above the last startable player at his position.

    Computed here rather than left to the pool's imputation because it is what
    makes the expert *rank* differ from the market's *ADP* in a realistic way: a
    quarterback outscores every running back and is still not ranked first,
    because the quarterback he replaces also scores a lot. Without a
    positionally-adjusted rank, ranks would put six QBs at the top of the board
    and every ADP-following manager would look like they were reaching wildly.
    """
    baselines: dict[Position, float] = {}
    for position, shape in POSITION_SHAPES.items():
        per_team = REPLACEMENT_RANK_PER_TEAM.get(position, 1.0)
        replacement_rank = max(1, min(shape.count, int(round(per_team * team_count))))
        baselines[position] = shape.points_at(replacement_rank)
    return {
        d.name: round(d.projection - baselines.get(d.position, 0.0), 1) for d in drafts
    }


def sample_player_frame(
    *,
    count: int = DEFAULT_PLAYER_COUNT,
    seed: int = SAMPLE_SEED,
    team_count: int = 12,
) -> pd.DataFrame:
    """A fictional player table in the app's own import format.

    Returned as a frame rather than a :class:`~models.player.PlayerPool` so it
    goes through :func:`services.importers.import_player_pool` exactly like a
    user's file — the sample data therefore exercises the real import path,
    including validation and imputation, instead of bypassing it.

    :param count: How many players to generate. Kept above a full draft's pick
        count so late rounds still involve a choice.
    :param seed: RNG seed; identical seeds produce identical pools.
    :param team_count: League size the replacement baselines are computed for.
        Only affects value-over-replacement and therefore the expert ranks.
    """
    rng = random.Random(seed)
    drafts = _generate(rng, max(24, int(count)))
    drafts.sort(key=lambda d: d.market_pick)
    vor = _value_over_replacement(drafts, int(team_count))

    # Expert rank orders by value over replacement; ADP orders by market price.
    # They agree broadly and disagree in the details, exactly as they do in real
    # data — which is what gives the "fallen past his ADP" lens something to find.
    by_value = sorted(drafts, key=lambda d: -vor.get(d.name, 0.0))
    value_rank = {d.name: index for index, d in enumerate(by_value, start=1)}

    rows: list[dict[str, object]] = []
    for index, draft in enumerate(drafts, start=1):
        adp = float(index)
        stdev = round(ADP_STDEV_FLOOR + ADP_STDEV_PER_PICK * adp, 2)
        # Platform ADP differs slightly from consensus, as it does in reality —
        # which is what makes the platform-vs-consensus ranking source setting a
        # meaningful choice rather than two names for one column.
        platform_adp = max(1.0, round(adp + rng.gauss(0.0, 1.0 + adp * 0.04), 1))
        rows.append({
            "player_name": draft.name,
            "position": str(draft.position),
            "nfl_team": draft.nfl_team,
            "bye_week": draft.bye_week,
            "experience": draft.experience,
            "rookie_flag": "Y" if draft.is_rookie else "N",
            "injury_status": str(draft.injury_status),
            "projection": draft.projection,
            "overall_rank": value_rank.get(draft.name, index),
            "position_rank": draft.position_rank,
            "platform_rank": index,
            "overall_adp": adp,
            "platform_adp": platform_adp,
            "adp_stdev": stdev,
            "min_pick": max(1, int(round(adp - 2.0 * stdev))),
            "max_pick": int(round(adp + 2.6 * stdev)),
            "ceiling": draft.ceiling,
            "floor": draft.floor,
            "risk_score": draft.risk_score,
            "value_over_replacement": vor.get(draft.name, ""),
            "notes": draft.notes,
        })
    return pd.DataFrame(rows, columns=list(PLAYER_IMPORT_COLUMNS))


def sample_pool_summary(frame: pd.DataFrame) -> pd.DataFrame:
    """Per-position summary of a generated pool, for the UI's data page."""
    if frame.empty:
        return pd.DataFrame()
    grouped = frame.groupby("position").agg(
        players=("player_name", "count"),
        best_adp=("overall_adp", "min"),
        median_projection=("projection", "median"),
        top_projection=("projection", "max"),
    )
    return grouped.reset_index().sort_values("best_adp").reset_index(drop=True)


__all__ = [
    "sample_player_frame", "sample_pool_summary", "POSITION_SHAPES",
    "SAMPLE_SEED", "DEFAULT_PLAYER_COUNT",
]
